---
resources:
  - ../base
patches:
  # Customize for external ceph cluster.
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: openshift-storage-client-ceph-rbd 
